#!/usr/bin/env python3
import argparse
import difflib
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request

GREEN = "\033[92m"
RED = "\033[91m"
RESET = "\033[0m"
STRIKETHROUGH = "\033[9m"

DEFAULT_MODEL = "qwen2.5-1.5b-instruct-q4_k_m.gguf"
MODEL_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def run_with_project_venv(error_if_missing: bool = False) -> None:
    """Re-run this script with the project virtual environment's Python.

    Lets beginners run ``python3 main.py`` or ``python3 transcribe_compare.py``
    right after ``./setup.sh`` without activating the virtual environment.
    Advanced users can still call the venv Python directly.
    """
    if os.name == "nt":
        venv_python = os.path.join(SCRIPT_DIR, "venv", "Scripts", "python.exe")
    else:
        venv_python = os.path.join(SCRIPT_DIR, "venv", "bin", "python3")
    if os.path.abspath(sys.executable) == os.path.abspath(venv_python):
        return
    if os.path.exists(venv_python):
        os.execv(venv_python, [venv_python] + sys.argv)
    if error_if_missing:
        print("Virtual environment not found. Run ./setup.sh first.", file=sys.stderr)
        sys.exit(1)

MERGE_SYSTEM_PROMPT = (
    "You are consolidating two transcripts of the same video recording. "
    "The EXISTING transcript is a prepared or previously reviewed version. "
    "The NEW transcript was generated by automatic speech recognition. "
    "Merge them into ONE clean, accurate transcript. Use the EXISTING transcript "
    "as the base: keep its wording and formatting where it is correct, and only "
    "adopt the NEW transcript's wording where the existing one has an error, a "
    "gap, or a missing or extra word. Fix punctuation, capitalization, and "
    "paragraph breaks for readability. Do not add commentary, notes, or "
    "explanations. Output only the merged transcript."
)


def transcribe_video(video_path: str, model_name: str = "base") -> str:
    import whisper

    model = whisper.load_model(model_name)
    result = model.transcribe(video_path)
    return result["text"].strip()


def save_transcription(text: str, output_path: str) -> None:
    with open(output_path, "w") as f:
        f.write(text + "\n")


def load_transcription(path: str) -> str:
    with open(path) as f:
        return f.read().strip()


def highlight_diffs(original: str, new: str) -> str:
    diff = difflib.unified_diff(
        original.splitlines(keepends=True),
        new.splitlines(keepends=True),
        fromfile="existing transcription",
        tofile="new transcription",
        lineterm="",
    )
    return "".join(diff)


def print_colored_diff(diff_text: str) -> None:
    for line in diff_text.splitlines():
        if line.startswith("+"):
            print(f"{GREEN}{line}{RESET}")
        elif line.startswith("-"):
            print(f"{RED}{line}{RESET}")
        else:
            print(line)


def diff_segments(original: str, new: str) -> list:
    """Compare two texts word by word.

    Returns a list of (kind, text) segments where kind is one of
    "equal", "delete", or "insert".
    """
    old_tokens = re.findall(r"\s+|\S+", original)
    new_tokens = re.findall(r"\s+|\S+", new)
    matcher = difflib.SequenceMatcher(None, old_tokens, new_tokens, autojunk=False)
    segments = []
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            segments.append(("equal", "".join(old_tokens[i1:i2])))
        elif tag == "delete":
            segments.append(("delete", "".join(old_tokens[i1:i2])))
        elif tag == "insert":
            segments.append(("insert", "".join(new_tokens[j1:j2])))
        else:  # replace
            segments.append(("delete", "".join(old_tokens[i1:i2])))
            segments.append(("insert", "".join(new_tokens[j1:j2])))
    return segments


def build_inline_diff(original: str, new: str) -> list:
    """Compare two transcriptions and lay the changes on top of each other.

    Unchanged lines are kept as-is. Changed lines are shown inline: removed
    text is wrapped in ``[- ... -]`` and added text in ``[+ ... +]``.
    """
    old_lines = original.splitlines(keepends=True)
    new_lines = new.splitlines(keepends=True)
    matcher = difflib.SequenceMatcher(None, old_lines, new_lines, autojunk=False)
    segments = []
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            for line in old_lines[i1:i2]:
                segments.append(("equal", line))
        elif tag == "delete":
            for line in old_lines[i1:i2]:
                segments.append(("delete", line))
        elif tag == "insert":
            for line in new_lines[j1:j2]:
                segments.append(("insert", line))
        else:  # replace
            old_block = "".join(old_lines[i1:i2])
            new_block = "".join(new_lines[j1:j2])
            segments.extend(diff_segments(old_block, new_block))
    return segments


def _symbolize(text: str, open_symbol: str, close_symbol: str) -> str:
    result = []
    for line in text.splitlines(keepends=True):
        content = line.rstrip("\n")
        if content:
            result.append(f"{open_symbol}{content}{close_symbol}")
        if line.endswith("\n"):
            result.append("\n")
    return "".join(result)


def render_diffs(segments: list) -> str:
    """Render diff segments to plain text using [+ ... +] and [- ... -] symbols."""
    out = []
    for kind, text in segments:
        if kind == "equal":
            out.append(text)
        elif kind == "delete":
            out.append(_symbolize(text, "[-", "-]"))
        else:
            out.append(_symbolize(text, "[+", "+]"))
    return "".join(out)


def _colorize(text: str, code: str, open_symbol: str, close_symbol: str) -> str:
    result = []
    for line in text.splitlines(keepends=True):
        content = line.rstrip("\n")
        if content:
            result.append(f"{code}{open_symbol}{content}{close_symbol}{RESET}")
        if line.endswith("\n"):
            result.append("\n")
    return "".join(result)


def print_diff_legend() -> None:
    print(
        f"Legend: {GREEN}[+ added text +]{RESET}  "
        f"{RED}{STRIKETHROUGH}[- removed text -]{RESET}"
    )


def print_inline_diff(segments: list) -> None:
    for kind, text in segments:
        if kind == "equal":
            sys.stdout.write(text)
        elif kind == "delete":
            sys.stdout.write(_colorize(text, RED + STRIKETHROUGH, "[-", "-]"))
        else:
            sys.stdout.write(_colorize(text, GREEN, "[+", "+]"))
    if not segments or not segments[-1][1].endswith("\n"):
        sys.stdout.write("\n")


def show_diffs(existing_text: str, new_text: str, diff_style: str = "inline") -> None:
    print("\n--- Differences ---")
    if existing_text == new_text:
        print("No differences found.")
        return
    if diff_style == "classic":
        diff_text = highlight_diffs(existing_text, new_text)
        if diff_text:
            print_colored_diff(diff_text)
    else:
        print_diff_legend()
        print_inline_diff(build_inline_diff(existing_text, new_text))


def default_model_path() -> str:
    return os.path.join(MODEL_DIR, DEFAULT_MODEL)


def build_merge_prompt(original: str, new: str) -> str:
    return (
        "=== EXISTING TRANSCRIPT ===\n"
        f"{original}\n\n"
        "=== NEW TRANSCRIPT ===\n"
        f"{new}\n\n"
        "=== MERGED TRANSCRIPT ==="
    )


def find_llama_server() -> str:
    override = os.environ.get("LLAMA_SERVER_BIN")
    if override:
        return override
    path = shutil.which("llama-server")
    if path:
        return path
    bundled = os.path.join(os.path.dirname(os.path.abspath(__file__)), "bin", "llama-server")
    if os.path.exists(bundled):
        return bundled
    raise RuntimeError(
        "llama-server was not found. Run ./setup.sh to install it, or set the "
        "LLAMA_SERVER_BIN environment variable."
    )


def _free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def _wait_ready(port: int, proc: subprocess.Popen, timeout: float = 180.0) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if proc.poll() is not None:
            raise RuntimeError(f"llama-server exited unexpectedly (code {proc.returncode}).")
        try:
            with urllib.request.urlopen(f"http://127.0.0.1:{port}/health", timeout=2) as resp:
                if "ok" in resp.read().decode():
                    return
        except Exception:
            pass
        time.sleep(1)
    raise RuntimeError("Timed out waiting for llama-server to start.")


def _chat_completion(port: int, system: str, user: str) -> str:
    payload = json.dumps(
        {
            "model": "llama",
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "temperature": 0.2,
            "stream": False,
        }
    ).encode()
    request = urllib.request.Request(
        f"http://127.0.0.1:{port}/v1/chat/completions",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=600) as resp:
            data = json.loads(resp.read().decode())
    except (urllib.error.URLError, OSError) as exc:
        raise RuntimeError(f"Local LLM request failed: {exc}") from exc
    return data["choices"][0]["message"]["content"].strip()


def query_local_llm(prompt: str, model_path: str) -> str:
    """Run one query against a local llama.cpp model.

    Starts llama-server for a single request and stops it afterwards, so no
    model stays resident in memory when idle.
    """
    if not os.path.exists(model_path):
        raise RuntimeError(
            f"Model file not found: {model_path}\nRun ./setup.sh to download it."
        )
    server_bin = find_llama_server()
    ngl = os.environ.get("LLAMA_NGL", "99")
    port = _free_port()
    proc = subprocess.Popen(
        [
            server_bin,
            "-m",
            model_path,
            "--port",
            str(port),
            "-c",
            "8192",
            "-ngl",
            ngl,
            "--no-webui",
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        _wait_ready(port, proc)
        return _chat_completion(port, MERGE_SYSTEM_PROMPT, prompt)
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()


def consolidate_transcripts(
    original: str, new: str, model_path: str = None
) -> str:
    if model_path is None:
        model_path = default_model_path()
    return query_local_llm(build_merge_prompt(original, new), model_path)


def merge_and_report(
    existing_text: str,
    new_text: str,
    model_path: str = None,
    output_path: str = None,
) -> str:
    if model_path is None:
        model_path = default_model_path()
    print(f"\nConsolidating transcripts with local model '{os.path.basename(model_path)}'...")
    merged = consolidate_transcripts(existing_text, new_text, model_path)
    print("\n--- Merged Transcript ---")
    print(merged)
    if output_path:
        save_transcription(merged, output_path)
        print(f"Merged transcript saved to: {output_path}")
    return merged


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Transcribe a video with Whisper and compare it to an existing transcription."
    )
    parser.add_argument("video", help="Path to the video file")
    parser.add_argument(
        "existing_transcription", help="Path to the existing transcription file"
    )
    parser.add_argument(
        "--model",
        default="base",
        choices=["tiny", "base", "small", "medium", "large"],
        help="Whisper model size (default: base)",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output path for the new transcription (default: <video_name>_transcript.txt)",
    )
    parser.add_argument(
        "--diff-style",
        default="inline",
        choices=["inline", "classic"],
        help="How to show the differences (default: inline)",
    )
    parser.add_argument(
        "--merge",
        action="store_true",
        help="Consolidate the existing and new transcripts into one clean transcript "
        "with a local LLM (default: off)",
    )
    parser.add_argument(
        "--merge-model",
        default=None,
        help="Path to the GGUF model for consolidation "
        "(default: the model bundled by setup.sh)",
    )
    parser.add_argument(
        "--merge-output",
        default=None,
        help="Where to save the merged transcript "
        "(default: <video_name>_merged.txt)",
    )
    args = parser.parse_args()

    if not os.path.exists(args.video):
        print(f"Error: video file not found: {args.video}", file=sys.stderr)
        sys.exit(1)

    if not os.path.exists(args.existing_transcription):
        print(
            f"Error: existing transcription file not found: {args.existing_transcription}",
            file=sys.stderr,
        )
        sys.exit(1)

    output_path = args.output or os.path.splitext(args.video)[0] + "_transcript.txt"

    print(f"Transcribing {args.video} with model '{args.model}'...")
    new_text = transcribe_video(args.video, args.model)

    save_transcription(new_text, output_path)
    print(f"New transcription saved to: {output_path}")

    existing_text = load_transcription(args.existing_transcription)

    show_diffs(existing_text, new_text, args.diff_style)

    if args.merge:
        merge_output = args.merge_output or os.path.splitext(args.video)[0] + "_merged.txt"
        merge_and_report(existing_text, new_text, args.merge_model, merge_output)


if __name__ == "__main__":
    run_with_project_venv()
    main()